### ISSUE TITLE
Installing stable doesn't work

### ISSUE THREAD

**Issue by tailhook** [edgedb/setup-edgedb#6]
https://github.com/edgedb/edgedb-js/runs/1552097452
The error is:
```
Starting EdgeDB test cluster...
Error: spawn edgedb-server-1-alpha6-dev5104 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

Not sure if this is an error of CLI or the action itself. Looks more like CLI because the package version is wrong, but I don't see CLI  output to debug the issue :(

**Comment by tailhook** [comment]
Oh, that was old env variable. Nevermind.
